### ISSUE TITLE
Scroll Delegate

### ISSUE THREAD

**Issue by Mohamed-Abden** [AlexBarinov/UIBubbleTableView#25]
I Wanna Make Certain Action When user Scroll To Top Where I Can Write This Action ?

**Comment by tuckerwales** [comment]
Hello,

As UIBubbleTableView is by extension a subclass of UIScrollView, it's delegate still receives the message -scrollViewDidScrollToTop: when the scroll view scrolls to top.

Thanks,

Joshua Lee Tucker
jlt

**Comment by Mohamed-Abden** [comment]
i Can Write This Method in UIBubbleTabelView But I Wanna Write It In My OwnViewController

**Comment by tuckerwales** [comment]
You need to set yourBubbleTableView.delegate = yourOwnViewController, in that case.

jlt

**Comment by Mohamed-Abden** [comment]
I cannot make BubbleTableView.delegate=Self;

**Comment by tuckerwales** [comment]
Why not?

**Comment by Mohamed-Abden** [comment]
because i didnot have Protocol with UIBubbleTableViewDelegate.

**Comment by Mohamed-Abden** [comment]
heeeeeeeeeeey

**Comment by AlexBarinov** [comment]
Implement 
- (void)scrollViewDidEndDecelerating:(UIScrollView *)scrollView
- (void)scrollViewDidEndDragging:(UIScrollView *)scrollView willDecelerate:(BOOL)decelerate
  in the delegate
