### ISSUE TITLE
Method deprecated causing not full resizing feature

### ISSUE THREAD

**Issue by amitkumar3968** [AlexBarinov/UIBubbleTableView#30]
HI, i would like to point that in uibubbletableview cell , 
- (UIImage *)stretchableImageWithLeftCapWidth:(NSInteger)leftCapWidth topCapHeight:(NSInteger)topCapHeight;
  is used for resing the bubble image but as of 
  xcode 4.5 and ios 5. it is deprecated and i am using the bubble demo in ios6.0. so the bubble image is sometimes not resizing properly...

**Comment by AlexBarinov** [comment]
Ok, any solution for this?

**Comment by amitkumar3968** [comment]
Hi Alex,
Thanks for reverting back, actually i am using this line of code for right now  in my  app. plz suggest for any better idea..
  self.bubbleImage.image = [[UIImage imageNamed:@"bubbleMine.png"] resizableImageWithCapInsets: UIEdgeInsetsMake(30, 40, 150, 150)   ];

**Comment by eliburke** [comment]
These cap insets appear to work properly with the included bubble images:

```
if (type == BubbleTypeSomeoneElse)
{
    self.bubbleImage.image = [[UIImage imageNamed:@"bubbleSomeone.png"] resizableImageWithCapInsets: UIEdgeInsetsMake(15, 21, 16, 21) ];
} else {
    self.bubbleImage.image = [[UIImage imageNamed:@"bubbleMine.png"] resizableImageWithCapInsets: UIEdgeInsetsMake(15, 21, 16, 21) ];
}
```

**Comment by amitkumar3968** [comment]
Thank you  Alex.
