### ISSUE TITLE
"order by" newer cells

### ISSUE THREAD

**Issue by fabiosoft** [AlexBarinov/UIBubbleTableView#35]
One doubt... is there some way to "override" auto ordering of the bubble table view?
I need newer to older order (newer in first row).
My data source provides me in that order and i want to keep it.

Thanks for your amazing job
Bye

**Comment by sibahota059** [comment]
Hey , the BubbleData is an Array of Objects. So you can Reverse that Before Reloading the Table view Right ?

NSArray\* reversed = [[myArray reverseObjectEnumerator] allObjects];

// Here Reload the BubbleTable.

**Comment by fabiosoft** [comment]
Hi, good idea...but i created a new method for doing that and reverse: reloadDataOrderby :)

Thanks
