### ISSUE TITLE
Additional UIlabel over the chat text left cornor. 

### ISSUE THREAD

**Issue by iTroyd23** [AlexBarinov/UIBubbleTableView#53]
i tried to add a time label over the left corner of the chat text. but the time lable was hidden if the previous chat item was an image. refer the image
![screen shot 2013-09-06 at 12 15 00 pm](https://f.cloud.github.com/assets/5397496/1094120/ceb6d6b6-16bf-11e3-9443-ec4f6b121088.png)

how can fix this. i modified insets of image and text

**Comment by burhan1875** [comment]
Hello,
i also try to display a time stamp next to the bubble. Can you please tell me how you realize this ?
Many thanks in advsance.
