### ISSUE TITLE
ARC support

### ISSUE THREAD

**Issue by BinaryDennis** [AlexBarinov/UIBubbleTableView#6]
Hi 
It would be really nice, and pretty easy to convert this project to be ARC friendly.
Basically Just remove all autorelase, retain and release statements.

**Comment by AlexBarinov** [comment]
Right, basically I would like to leave non-ARC support as well. There should be a def checked (i.e. #define ARC_ENABLED).

**Comment by BinaryDennis** [comment]
yeah, this sounds like the best solution.

**Comment by hoan** [comment]
+1 for this, just testing this now with an ARC project

**Comment by AlexBarinov** [comment]
Should be there with the last commit.
There's ARC_ENABLED macro defined in *.pch file (commented by default). To make the code ARC compatible, uncomment it (or define the same in your project).

Can anybody verify it please?
