### ISSUE TITLE
Image support would be nice

### ISSUE THREAD

**Issue by BinaryDennis** [AlexBarinov/UIBubbleTableView#7]
Hi
Great project. The only thing missing in this project to be a perfect chatTableView is support for photos. 

Users expect, just like the built-in Message app in iOS, to be able to send photos to each other along side with the message text. And when they press the photo in the tableview they should be able to see a fullscreen view of the photo.

Is it possible for you to implement photo support within the next 2 coming months? 

Br
Dennis

**Comment by zhengwu119** [comment]
Right,wish too.

**Comment by ieliwb** [comment]
Right,wish too.

**Comment by AlexBarinov** [comment]
Image bubbles are now there. Check the site or example to see how it looks like. Use table delegate to perform any action you want when user clicks the image.

**Comment by BinaryDennis** [comment]
Excellent job! Thank you very much, appreciate it.
