### ISSUE TITLE
I will donate $100 if someone ports this correct to Xamarin C#

### ISSUE THREAD

**Issue by JohnnyWonder** [AlexBarinov/UIBubbleTableView#81]
I am serious.  If it can be made to work at Xamarin in C# for iOS and (bonus more money for Android too) I will PayPal $100 to the person.

**Comment by capriele** [comment]
Hi! I'm interested to this work. If you want I can port it to Xamarin. 
Regards

**Comment by capriele** [comment]
I've ported this work to Xamarin C#. If you want you can contact me.

**Comment by JohnnyWonder** [comment]
How do I contact you?  I am new to this site...  I will make good on my pledge if it can be proved to me that it works.  One question...  is it possible to make a growing text view where the message is typed in?

**Comment by capriele** [comment]
You can contact me via email: petrucci.alberto@gmail.com.
If you want i can implement a growing text but this requires additional work.

**Comment by JohnnyWonder** [comment]
Thank you Alberto Petrucci.  He did it... paid as promised.  Issue closed.
