### ISSUE TITLE
Got warning: Unable to simultaneously satisfy constraints.

### ISSUE THREAD

**Issue by ipeisong** [AlexBarinov/UIBubbleTableView#9]
I'm not sure how this happens, but this is the log:

2012-10-12 15:12:24.370 gdt-iphone[20333:c07] Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0xc8ee9d0 h=-&- v=-&- UIViewControllerWrapperView:0xc83d6f0.height == UINavigationTransitionView:0xa7957e0.height - 44>",
    "<NSAutoresizingMaskLayoutConstraint:0xc865730 h=-&- v=-&- UILayoutContainerView:0xa793040.height == UIView:0xb362280.height>",
    "<NSAutoresizingMaskLayoutConstraint:0xb3965a0 h=-&- v=-&- UINavigationTransitionView:0xa7957e0.height == UILayoutContainerView:0xa793040.height>",
    "<NSAutoresizingMaskLayoutConstraint:0xc88c810 h=--- v=--- V:[UIWindow:0xa78fc20(480)]>",
    "<NSAutoresizingMaskLayoutConstraint:0xc88b220 h=-&- v=-&- UIView:0xb362280.height == UIWindow:0xa78fc20.height - 20>",
    "<NSLayoutConstraint:0x1936fc30 V:[GBubbleTableView:0xd113600(462)]>",
    "<NSLayoutConstraint:0x1939bd80 V:[GBubbleTableView:0xd113600]-(42)-|   (Names: '|':UIView:0x1939b610 )>",
    "<NSAutoresizingMaskLayoutConstraint:0xc851d30 h=-&- v=-&- UIView:0x1939b610.height == UIViewControllerWrapperView:0xc83d6f0.height>",
    "<NSLayoutConstraint:0x1939bd40 V:|-(0)-[GBubbleTableView:0xd113600]   (Names: '|':UIView:0x1939b610 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x1936fc30 V:[GBubbleTableView:0xd113600(462)]>

Break on objc_exception_throw to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

**Comment by ipeisong** [comment]
2012-10-12 15:12:24.370 gdt-iphone[20333:c07] Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    " < NSAutoresizingMaskLayoutConstraint:0xc8ee9d0 h=-&- v=-&- UIViewControllerWrapperView:0xc83d6f0.height == UINavigationTransitionView:0xa7957e0.height - 44>",
    " < NSAutoresizingMaskLayoutConstraint:0xc865730 h=-&- v=-&- UILayoutContainerView:0xa793040.height == UIView:0xb362280.height>",
    " < NSAutoresizingMaskLayoutConstraint:0xb3965a0 h=-&- v=-&- UINavigationTransitionView:0xa7957e0.height == UILayoutContainerView:0xa793040.height>",
    " < NSAutoresizingMaskLayoutConstraint:0xc88c810 h=--- v=--- V:[UIWindow:0xa78fc20(480)]>",
    " < NSAutoresizingMaskLayoutConstraint:0xc88b220 h=-&- v=-&- UIView:0xb362280.height == UIWindow:0xa78fc20.height - 20>",
    " < NSLayoutConstraint:0x1936fc30 V:[GBubbleTableView:0xd113600(462)]>",
    " < NSLayoutConstraint:0x1939bd80 V:[GBubbleTableView:0xd113600]-(42)-|   (Names: '|':UIView:0x1939b610 )>",
    " < NSAutoresizingMaskLayoutConstraint:0xc851d30 h=-&- v=-&- UIView:0x1939b610.height == UIViewControllerWrapperView:0xc83d6f0.height>",
    " < NSLayoutConstraint:0x1939bd40 V:|-(0)-[GBubbleTableView:0xd113600](Names: '|':UIView:0x1939b610)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x1936fc30 V:[GBubbleTableView:0xd113600(462)]>

Break on objc_exception_throw to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

**Comment by AlexBarinov** [comment]
Can you send me the code to reproduce and your environment to github@alex.barinov.name, please?

**Comment by ipeisong** [comment]
Seems it only happens in iOS 6 with auto layout enabled. I have changed my project to not to use auto layout and the warning has gone. :p
